package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallStock;
import org.linlinjava.litemall.db.domain.LitemallStockExample;

public interface LitemallStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    long countByExample(LitemallStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int insert(LitemallStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int insertSelective(LitemallStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    LitemallStock selectOneByExample(LitemallStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    LitemallStock selectOneByExampleSelective(@Param("example") LitemallStockExample example, @Param("selective") LitemallStock.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    List<LitemallStock> selectByExampleSelective(@Param("example") LitemallStockExample example, @Param("selective") LitemallStock.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    List<LitemallStock> selectByExample(LitemallStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    LitemallStock selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallStock.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    LitemallStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    LitemallStock selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallStock record, @Param("example") LitemallStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallStock record, @Param("example") LitemallStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}