package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallWarehouse;
import org.linlinjava.litemall.db.domain.LitemallWarehouseExample;

public interface LitemallWarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    long countByExample(LitemallWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int insert(LitemallWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int insertSelective(LitemallWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    LitemallWarehouse selectOneByExample(LitemallWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    LitemallWarehouse selectOneByExampleSelective(@Param("example") LitemallWarehouseExample example, @Param("selective") LitemallWarehouse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    List<LitemallWarehouse> selectByExampleSelective(@Param("example") LitemallWarehouseExample example, @Param("selective") LitemallWarehouse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    List<LitemallWarehouse> selectByExample(LitemallWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    LitemallWarehouse selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallWarehouse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    LitemallWarehouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    LitemallWarehouse selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallWarehouse record, @Param("example") LitemallWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallWarehouse record, @Param("example") LitemallWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_warehouse
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}